# Generated by Django 4.1.7 on 2023-03-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=140)),
                ('nom', models.CharField(blank=True, max_length=140)),
                ('numero', models.IntegerField(default=0)),
                ('nombreVote', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
