# Generated by Django 4.1.7 on 2023-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0003_transaction_souscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=140)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=140)),
                ('nom', models.CharField(blank=True, max_length=140)),
                ('numero', models.IntegerField(default=0)),
                ('nombreVote', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('age', models.IntegerField(default=0)),
                ('projet', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='projet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nom',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
