# Generated by Django 4.1.7 on 2023-03-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0004_actualites_candidat_candidate_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscription',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='miss.candidate'),
        ),
    ]
