# Generated by Django 4.1.7 on 2023-03-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0007_souscription_candidat_alter_souscription_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscription',
            name='candidat',
        ),
    ]
