# Generated by Django 4.1.7 on 2023-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0009_souscription_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualites',
            name='auteur',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='actualites',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
