# Generated by Django 4.1.7 on 2023-03-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0010_actualites_auteur_actualites_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualites',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='actualites',
            name='image2',
        ),
    ]
