# Generated by Django 4.1.7 on 2023-03-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0011_remove_actualites_image1_remove_actualites_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='nombreVote',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nombreVote',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
