# Generated by Django 4.1.7 on 2023-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miss", "0012_alter_candidat_nombrevote_alter_candidate_nombrevote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(default="", max_length=100)),
                ("message", models.CharField(default="", max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
