# Generated by Django 4.1.7 on 2023-03-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("miss", "0013_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="souscription",
            name="candidat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="miss.candidat",
            ),
        ),
        migrations.AlterField(
            model_name="souscription",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="miss.candidate",
            ),
        ),
    ]
